'use client';
import { ArrowUpRight } from 'lucide-react';
import { experienceContent as content, siteContent } from '@/content/site-content';
import { contact } from '@/lib/content';
import { MotionLink, Reveal, useMotionPreferences } from '../motion';

export function FooterExperience() {
  const { ambient } = useMotionPreferences();
  const links = [{ title: contact.email, href: contact.emailHref }, { title: 'WhatsApp', href: contact.whatsappHref }, { title: 'Instagram', href: contact.instagram }, { title: 'LinkedIn', href: contact.linkedin }].filter(link => Boolean(link.href));
  return <footer className="x-footer x-section" data-theme="dark" data-ambient="footer" onFocusCapture={() => { if (ambient && (document.querySelector('.experience-main')?.getBoundingClientRect().bottom ?? 0) > innerHeight) window.scrollTo({ top: document.documentElement.scrollHeight, behavior: 'instant' }); }}><div className="x-container"><div className="experience-footer-top"><Reveal><span className="x-kicker">{content.footer.note}</span><p>{siteContent.copy.home.diseno_con_caracter}<br />{siteContent.copy.home.experiencias_con_proposito}</p>{contact.address && <p>{contact.address}</p>}</Reveal><Reveal delay={.08}><nav aria-label="Servicios del estudio">{siteContent.footerServices.map(({ label, link }) => <MotionLink key={label} href={siteContent.links[link as keyof typeof siteContent.links]}>{label}</MotionLink>)}</nav></Reveal><Reveal delay={.16}><span className="x-kicker">{content.footer.contact}</span><nav aria-label="Contacto y redes">{links.map(link => <a key={link.title} href={link.href} {...(link.href.startsWith('https') ? { target: '_blank', rel: 'noopener noreferrer' } : {})}>{link.title}<ArrowUpRight size={15} /></a>)}</nav></Reveal></div><MotionLink className="footer-giant-wordmark" href={siteContent.links.home} aria-label="Velour Studio, inicio"><span>VELOUR</span><small>{content.footer.studio}</small><ArrowUpRight aria-hidden="true" /></MotionLink><div className="experience-footer-bottom"><span>{siteContent.copy.home.text_2026_velour_studio}</span><div><MotionLink href={siteContent.links.privacy}>{siteContent.copy.home.privacy}</MotionLink><MotionLink href={siteContent.links.terms}>{siteContent.copy.home.terms}</MotionLink></div><MotionLink href={siteContent.links.home}>{siteContent.copy.home.volver_arriba}<ArrowUpRight size={12} /></MotionLink></div></div></footer>;
}
