import { siteContent } from '@/content/site-content';
import Image from 'next/image';

/** Public-facing website and identity concepts, composed as editorial artwork. */
export function ProjectMockup({ kind, eager = false }: { kind: string; eager?: boolean }) {
  if (kind === 'fashion') return <div className="project-art fashion-art"><div className="fashion-site"><div className="fashion-nav"><span className="fashion-logo">{siteContent.copy.demoArtwork.maison}</span><span>{siteContent.copy.demoArtwork.coleccion_filosofia}</span><span>{siteContent.copy.demoArtwork.es}</span></div><div className="fashion-main"><div className="fashion-copy"><span>{siteContent.copy.demoArtwork.el_arte_de_vestir_lo_esencial}</span><div className="mock-title">{siteContent.copy.demoArtwork.menos}<br /><em>{siteContent.copy.demoArtwork.pero_mejor}</em></div><p>{siteContent.copy.demoArtwork.prendas_que_permanecen}<br />{siteContent.copy.demoArtwork.una_nueva_forma_de_habitar_lo_cotidiano}</p><span className="fashion-cta">{siteContent.copy.demoArtwork.descubrir_la_coleccion}</span><small>{siteContent.copy.demoArtwork.coleccion_01_2026}</small></div><div className="fashion-photo"><Image src={siteContent.media.demoFashion.src} alt={siteContent.media.demoFashion.alt} loading={eager ? 'eager' : 'lazy'} fill sizes="(max-width: 540px) 47vw, (max-width: 1440px) 42vw, 558px" /></div></div><div className="fashion-bottom"><span>{siteContent.copy.demoArtwork.diseno_atemporal}</span><span>{siteContent.copy.demoArtwork.piezas_con_intencion}</span></div></div><span className="art-context">{siteContent.copy.demoArtwork.maison_direccion_de_arte_comercio_digital}</span></div>;
  if (kind === 'recruitment') return <div className="project-art recruitment-art"><div className="recruitment-site"><div className="recruitment-nav"><strong>{siteContent.copy.demoArtwork.recruit}<span>{siteContent.copy.demoArtwork.symbol}</span></strong><span>{siteContent.copy.demoArtwork.personas_posibilidades}</span><span>{siteContent.copy.demoArtwork.conectemos}</span></div><div className="recruitment-main"><span>{siteContent.copy.demoArtwork.donde_empieza_lo_que_viene}</span><div className="mock-title">{siteContent.copy.demoArtwork.el_talento}<br />{siteContent.copy.demoArtwork.cambia}<em>{siteContent.copy.demoArtwork.todo}</em></div><div className="recruitment-graphic" aria-hidden="true"><i /><i /><i /><i /></div><div className="recruitment-foot"><p>{siteContent.copy.demoArtwork.conectamos_tu_proximo_paso}<br />{siteContent.copy.demoArtwork.con_nuevas_posibilidades}</p><span>{siteContent.copy.demoArtwork.encontra_tu_lugar}</span></div></div></div><span className="art-context">{siteContent.copy.demoArtwork.recruitment_una_nueva_perspectiva_del_talento}</span></div>;
  return <div className="project-art identity-art"><div className="identity-sheet"><span className="identity-label">{siteContent.copy.demoArtwork.el_valor_de_lo_esencial}</span><div className="identity-monogram">{siteContent.copy.demoArtwork.a}<span>{siteContent.copy.demoArtwork.t}</span></div><div className="identity-name">{siteContent.copy.demoArtwork.atelier}<small>{siteContent.copy.demoArtwork.objetos_con_alma}</small></div><span className="identity-sheet-bottom">{siteContent.copy.demoArtwork.identidad_est_2026}</span></div><div className="identity-card"><span>{siteContent.copy.demoArtwork.atelier}</span><small>{siteContent.copy.demoArtwork.lo_cotidiano}<br /><em>{siteContent.copy.demoArtwork.extraordinario}</em></small><span className="identity-card-line" /></div><div className="identity-seal" aria-hidden="true">{siteContent.copy.demoArtwork.a_2}</div><span className="art-context">{siteContent.copy.demoArtwork.atelier_sistema_de_identidad_visual}</span></div>;
}
